name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.Main"
authors: [erudo,Koryu25]
api-version: 1.13
depend: [QualityArmory]
commands:
  emj:
    description: EMine-Jobs Plugin